---
- src: https://github.com/bossjones/boss-ansible-role-debug
- src: https://github.com/bossjones/ansible-role-tmux

- src: https://github.com/zzet/ansible-rbenv-role
  name: zzet.rbenv
  version: 3.3.6

- src: https://github.com/Oefenweb/ansible-fail2ban
- src: https://github.com/juju4/ansible-maxmind
  name: juju4.maxmind
- src: https://github.com/juju4/ansible-ipsumdump
  name: juju4.ipsumdump
- src: https://github.com/juju4/ansible-redhat-epel
  name: juju4.redhat_epel
