---

- set_fact:
    mysql_svc: mysql
    mysql_confdir: /etc/mysql
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- set_fact:
    mysql_svc: mariadb
    mysql_confdir: /etc/my.cnf.d
  when: ansible_os_family == "RedHat"
