---

- block:
    - include: pip-upgrade.yml
## AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
    - name: PyOpenSSL 16.2+
      pip:
        name: pyopenssl
        version: 17.2.0
        state: present
      register: pkg_result
      until: pkg_result is success
  when: ansible_distribution_release == 'xenial'
#  when: ansible_distribution_release == 'xenial' or ansible_distribution_major_version|int <= 7
