---

## setup var is set during setup phase. means we always fail on first run if not already install...
##  was only necessary ansible_lsb var. now using ansible_distribution_major_version
#- name: Redhat | Install lsb-core
#  yum: name=redhat-lsb state=present

## force to gather facts again because of redhat-lsb
#- action: setup
#- debug: var=ansible_lsb

- name: RHEL | Install Bro yum repository
  get_url:
    url: >
      https://download.opensuse.org/repositories/network:bro/CentOS_{{ ansible_distribution_major_version }}/network:bro.repo
    dest: /etc/yum.repos.d/bro.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"
- name: Fedora | Install Bro yum repository
  get_url:
    url: >
      https://download.opensuse.org/repositories/network:bro/Fedora_{{ ansible_distribution_major_version }}/network:bro.repo
    dest: /etc/yum.repos.d/bro.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Fedora"

# opensuse mirror has issue sometimes
# https://central.owncloud.org/t/client-install-redhat-repository-download-fails/9459/6
# https://bugzilla.redhat.com/show_bug.cgi?id=1055478
- name: opensuse mirror workaround | lower yum minrate
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^minrate=.*'
    line: 'minrate=100'
    backup: yes
# repositories does not seem to be mirrored as much as distribution (subset of https://mirrors.opensuse.org/)
- name: opensuse mirror workaround | review mirror
  replace:
    dest: /etc/yum.repos.d/bro.repo
    regexp: "^baseurl=.*/repositories/network:/bro/"
    replace: "baseurl={{ bro_opensuse_rpm_mirror }}"
    backup: yes

## FIXME! travis: skipping + "[Errno 30] Read-only file system"
- name: Redhat | Install Bro and dependencies
  yum: name={{ broids_packages + broids_packages_deps }} state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success

- name: update broctl LogDir
  replace:
    dest: "{{ broids_etc }}/broctl.cfg"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: '^LogDir = .*', rep: "LogDir = {{ broids_log }}" }
    - { re: '^SpoolDir = .*', rep: "SpoolDir = {{ broids_spool }}" }

- name: update broctl LogDir - missing line
  lineinfile:
    dest: "{{ broids_etc }}/broctl.cfg"
    regexp: "{{ item.re }}"
    line: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: '^LibDirInternal = .*', rep: "LibDirInternal = {{ broids_libdir }}" }
    - { re: '^PluginDir = .*', rep: "PluginDir = {{ broids_plugindir }}" }

- name: Redhat | Ensure Mysql/Mariadb is running and enabled on boot.
  service: "name={{ mysql_svc }} state=started enabled=yes"
