---
- name: restart bro
  command: "{{ broids_broctl }} restart"

- name: restart monit
  service: name=monit state=restarted

- name: fetch critical-stack-intel feeds
  command: critical-stack-intel pull

- name: Restart apparmor
  service: name=apparmor state=restarted
  when: travisci is defined and travisci
